alias ll="ls -lah"
# MY_FILE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
# MY_DIR_PATH=$(echo $MY_FILE_PATH | awk -F"/" '{ for (i = 1; i <= NF-2; i++) { printf "%s%s", $i, "/" } printf $(NF-1) }')
# export LD_LIBRARY_PATH=$MY_DIR_PATH/../lib:${LD_LIBRARY_PATH}
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ath_usr
